version: '3'
services:
  ml_server:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: streamlit_analyzer
    container_name: streamlit_analyzer

    tty: true

    ports:
      - "8889:8888"
      - "8502:8501"

    volumes:
      - ./src:/src